### ISSUE TITLE
constant -536870212 overflows uint64 - high sierra - 17C85a

### ISSUE THREAD

**Issue by johndpope** [ethanfrey/ledger#1]
➜  ledger git:(master) make install
go install ./cmd/ledger
# github.com/ethanfrey/hid
../ethanfrey/hid/hid_darwin.go:47: constant -536870212 overflows uint64
../ethanfrey/hid/hid_darwin.go:48: constant -536870211 overflows uint64
../ethanfrey/hid/hid_darwin.go:49: constant -536870210 overflows uint64
../ethanfrey/hid/hid_darwin.go:50: constant -536870209 overflows uint64
../ethanfrey/hid/hid_darwin.go:51: constant -536870208 overflows uint64
../ethanfrey/hid/hid_darwin.go:52: constant -536870207 overflows uint64
../ethanfrey/hid/hid_darwin.go:53: constant -536870206 overflows uint64
../ethanfrey/hid/hid_darwin.go:54: constant -536870205 overflows uint64
../ethanfrey/hid/hid_darwin.go:55: constant -536870204 overflows uint64
../ethanfrey/hid/hid_darwin.go:56: constant -536870203 overflows uint64
../ethanfrey/hid/hid_darwin.go:56: too many errors
make: *** [install] Error 2

**SEPARATE PROBLEM**
trying to build basecoin - https://github.com/tendermint/ comos
but failing / suspect it's due to this library dependency.

cosmos-sdk git:(master) ✗ make all
[WARN]	The name listed in the config file (github.com/cosmos/cosmos-sdk) does not match the current location (.)
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/bgentry/speakeasy 4aabc24848ce5fd31929f7d1e4ea74d3709c14cd!
[INFO]	--> Found desired version locally github.com/btcsuite/btcd 2e60448ffcc6bf78332d1fe590260095f554dd78!
[INFO]	--> Found desired version locally github.com/BurntSushi/toml a368813c5e648fee92e5f6c30e3944ff9d5e8895!
[INFO]	--> Found desired version locally github.com/ebuchman/fail-test 95f809107225be108efcf10a3509e4ea6ceef3c4!
[INFO]	--> Found desired version locally github.com/ethanfrey/hid dce75af84cf849c60f39bf1b8192fb5cd597b5d9!
[INFO]	--> Found desired version locally github.com/ethanfrey/ledger f7f2f056357db77db845a79aa1abdadc3ae66369!
[INFO]	--> Found desired version locally github.com/fsnotify/fsnotify 4da3e2cfbabc9f751898f250b49f2439785783a1!
[INFO]	--> Found desired version locally github.com/go-kit/kit 953e747656a7bbb5e1f998608b460458958b70cc!
[INFO]	--> Found desired version locally github.com/go-logfmt/logfmt 390ab7935ee28ec6b286364bba9b4dd6410cb3d5!
[INFO]	--> Found desired version locally github.com/go-playground/locales e4cbcb5d0652150d40ad0646651076b6bd2be4f6!
[INFO]	--> Found desired version locally github.com/go-playground/universal-translator 71201497bace774495daed26a3874fd339e0b538!
[INFO]	--> Found desired version locally github.com/go-stack/stack 259ab82a6cad3992b4e21ff5cac294ccb06474bc!
[INFO]	--> Found desired version locally github.com/gogo/protobuf 342cbe0a04158f6dcb03ca0079991a51a4248c02!
[INFO]	--> Found desired version locally github.com/golang/protobuf 1e59b77b52bf8e4b449a57e6f79f21226d571845!
[INFO]	--> Found desired version locally github.com/golang/snappy 553a641470496b2327abcac10b36396bd98e45c9!
[INFO]	--> Found desired version locally github.com/gorilla/context 08b5f424b9271eedf6f9f0ce86cb9396ed337a42!
[INFO]	--> Found desired version locally github.com/gorilla/mux 5ab525f4fb1678e197ae59401e9050fa0b6cb5fd!
[INFO]	--> Found desired version locally github.com/gorilla/websocket ea4d1f681babbce9545c9c5f3d5194a789c89f5b!
[INFO]	--> Found desired version locally github.com/hashicorp/hcl 23c074d0eceb2b8a5bfdbb271ab780cde70f05a8!
[INFO]	--> Found desired version locally github.com/howeyc/crc16 2b2a61e366a66d3efb279e46176e7291001e0354!
[INFO]	--> Found desired version locally github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75!
[INFO]	--> Found desired version locally github.com/jmhodges/levigo c42d9e0ca023e2198120196f842701bb4c55d7b9!
[INFO]	--> Found desired version locally github.com/kr/logfmt b84e30acd515aadc4b783ad4ff83aff3299bdfe0!
[INFO]	--> Found desired version locally github.com/magiconair/properties 49d762b9817ba1c2e9d0c69183c2b4a8b8f1d934!
[INFO]	--> Found desired version locally github.com/mattn/go-isatty 6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c!
[INFO]	--> Found desired version locally github.com/mitchellh/mapstructure 06020f85339e21b2478f756a78e295255ffa4d6a!
[INFO]	--> Found desired version locally github.com/pelletier/go-toml 0131db6d737cfbbfb678f8b7d92e55e27ce46224!
[INFO]	--> Found desired version locally github.com/pkg/errors 645ef00459ed84a119197bfb8d8205042c6df63d!
[INFO]	--> Found desired version locally github.com/rcrowley/go-metrics e181e095bae94582363434144c61a9653aff6e50!
[INFO]	--> Found desired version locally github.com/spf13/afero 57afd63c68602b63ed976de00dd066ccb3c319db!
[INFO]	--> Found desired version locally github.com/spf13/cast acbeb36b902d72a7a4c18e8f3241075e7ab763e4!
[INFO]	--> Found desired version locally github.com/spf13/cobra 7b2c5ac9fc04fc5efafb60700713d4fa609b777b!
[INFO]	--> Found desired version locally github.com/spf13/jwalterweatherman 12bd96e66386c1960ab0f74ced1362f66f552f7b!
[INFO]	--> Found desired version locally github.com/spf13/pflag 4c012f6dcd9546820e378d0bdda4d8fc772cdfea!
[INFO]	--> Found desired version locally github.com/spf13/viper aafc9e6bc7b7bb53ddaa75a5ef49a17d6e654be5!
[INFO]	--> Found desired version locally github.com/syndtr/goleveldb 34011bf325bce385408353a30b101fe5e923eb6e!
[INFO]	--> Found desired version locally github.com/tendermint/abci 5d5ea6869b91cadb55dbc4211ad7b326f053a33e!
[INFO]	--> Found desired version locally github.com/tendermint/ed25519 d8387025d2b9d158cf4efb07e7ebf814bcce2057!
[INFO]	--> Found desired version locally github.com/tendermint/go-crypto dd20358a264c772b4a83e477b0cfce4c88a7001d!
[INFO]	--> Found desired version locally github.com/tendermint/go-wire b6fc872b42d41158a60307db4da051dd6f179415!
[INFO]	--> Found desired version locally github.com/tendermint/iavl 594cc0c062a7174475f0ab654384038d77067917!
[INFO]	--> Found desired version locally github.com/tendermint/tendermint 381fe19335ba8825e04d1d0fefa5cac709bb7178!
[INFO]	--> Found desired version locally github.com/tendermint/tmlibs 91b4b534ad78e442192c8175db92a06a51064064!
[INFO]	--> Found desired version locally golang.org/x/crypto 0fcca4842a8d74bfddc2c96a073bd2a4d2a7a2e8!
[INFO]	--> Found desired version locally golang.org/x/net 42fe2e1c20de1054d3d30f82cc9fb5b41e2e3767!
[INFO]	--> Found desired version locally golang.org/x/sys a3f2cbd54cf5dfe3fbaccf76375fdb12f67654c8!
[INFO]	--> Found desired version locally golang.org/x/text e19ae1496984b1c655b8044a65c0300a3c878dd3!
[INFO]	--> Found desired version locally google.golang.org/genproto a8101f21cf983e773d0c1133ebc5424792003214!
[INFO]	--> Found desired version locally google.golang.org/grpc 401e0e00e4bb830a10496d64cd95e068c5bf50de!
[INFO]	--> Found desired version locally gopkg.in/go-playground/validator.v9 b1f51f36f1c98cc97f777d6fc9d4b05eaa0cabb5!
[INFO]	--> Found desired version locally gopkg.in/yaml.v2 0e4404da71227dcc02fb1deee803d93e86d08f72!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew ecdeabc65495df2dec95d7c4a4c3e021903035e5!
[INFO]	--> Found desired version locally github.com/pmezard/go-difflib 792786c7400a136282c1664665ae0a8db921c6c2!
[INFO]	--> Found desired version locally github.com/stretchr/testify 87b1dfb5b2fa649f52695dd9eae19abe404a4308!
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/go-stack/stack to 259ab82a6cad3992b4e21ff5cac294ccb06474bc.
[INFO]	--> Setting version for github.com/gorilla/websocket to ea4d1f681babbce9545c9c5f3d5194a789c89f5b.
[INFO]	--> Setting version for github.com/ethanfrey/hid to dce75af84cf849c60f39bf1b8192fb5cd597b5d9.
[INFO]	--> Setting version for github.com/BurntSushi/toml to a368813c5e648fee92e5f6c30e3944ff9d5e8895.
[INFO]	--> Setting version for github.com/gorilla/mux to 5ab525f4fb1678e197ae59401e9050fa0b6cb5fd.
[INFO]	--> Setting version for github.com/golang/protobuf to 1e59b77b52bf8e4b449a57e6f79f21226d571845.
[INFO]	--> Setting version for github.com/golang/snappy to 553a641470496b2327abcac10b36396bd98e45c9.
[INFO]	--> Setting version for github.com/go-kit/kit to 953e747656a7bbb5e1f998608b460458958b70cc.
[INFO]	--> Setting version for github.com/btcsuite/btcd to 2e60448ffcc6bf78332d1fe590260095f554dd78.
[INFO]	--> Setting version for github.com/hashicorp/hcl to 23c074d0eceb2b8a5bfdbb271ab780cde70f05a8.
[INFO]	--> Setting version for github.com/ebuchman/fail-test to 95f809107225be108efcf10a3509e4ea6ceef3c4.
[INFO]	--> Setting version for github.com/bgentry/speakeasy to 4aabc24848ce5fd31929f7d1e4ea74d3709c14cd.
[INFO]	--> Setting version for github.com/fsnotify/fsnotify to 4da3e2cfbabc9f751898f250b49f2439785783a1.
[INFO]	--> Setting version for github.com/go-playground/universal-translator to 71201497bace774495daed26a3874fd339e0b538.
[INFO]	--> Setting version for github.com/howeyc/crc16 to 2b2a61e366a66d3efb279e46176e7291001e0354.
[INFO]	--> Setting version for github.com/go-playground/locales to e4cbcb5d0652150d40ad0646651076b6bd2be4f6.
[INFO]	--> Setting version for github.com/gogo/protobuf to 342cbe0a04158f6dcb03ca0079991a51a4248c02.
[INFO]	--> Setting version for github.com/gorilla/context to 08b5f424b9271eedf6f9f0ce86cb9396ed337a42.
[INFO]	--> Setting version for github.com/ethanfrey/ledger to f7f2f056357db77db845a79aa1abdadc3ae66369.
[INFO]	--> Setting version for github.com/go-logfmt/logfmt to 390ab7935ee28ec6b286364bba9b4dd6410cb3d5.
[INFO]	--> Setting version for github.com/jmhodges/levigo to c42d9e0ca023e2198120196f842701bb4c55d7b9.
[INFO]	--> Setting version for github.com/inconshreveable/mousetrap to 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75.
[INFO]	--> Setting version for github.com/kr/logfmt to b84e30acd515aadc4b783ad4ff83aff3299bdfe0.
[INFO]	--> Setting version for github.com/magiconair/properties to 49d762b9817ba1c2e9d0c69183c2b4a8b8f1d934.
[INFO]	--> Setting version for github.com/mattn/go-isatty to 6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c.
[INFO]	--> Setting version for github.com/spf13/jwalterweatherman to 12bd96e66386c1960ab0f74ced1362f66f552f7b.
[INFO]	--> Setting version for github.com/rcrowley/go-metrics to e181e095bae94582363434144c61a9653aff6e50.
[INFO]	--> Setting version for github.com/pelletier/go-toml to 0131db6d737cfbbfb678f8b7d92e55e27ce46224.
[INFO]	--> Setting version for github.com/spf13/cobra to 7b2c5ac9fc04fc5efafb60700713d4fa609b777b.
[INFO]	--> Setting version for github.com/spf13/afero to 57afd63c68602b63ed976de00dd066ccb3c319db.
[INFO]	--> Setting version for github.com/spf13/viper to aafc9e6bc7b7bb53ddaa75a5ef49a17d6e654be5.
[INFO]	--> Setting version for github.com/pkg/errors to 645ef00459ed84a119197bfb8d8205042c6df63d.
[INFO]	--> Setting version for github.com/mitchellh/mapstructure to 06020f85339e21b2478f756a78e295255ffa4d6a.
[INFO]	--> Setting version for github.com/spf13/pflag to 4c012f6dcd9546820e378d0bdda4d8fc772cdfea.
[INFO]	--> Setting version for github.com/spf13/cast to acbeb36b902d72a7a4c18e8f3241075e7ab763e4.
[INFO]	--> Setting version for github.com/tendermint/abci to 5d5ea6869b91cadb55dbc4211ad7b326f053a33e.
[INFO]	--> Setting version for github.com/syndtr/goleveldb to 34011bf325bce385408353a30b101fe5e923eb6e.
[INFO]	--> Setting version for github.com/tendermint/ed25519 to d8387025d2b9d158cf4efb07e7ebf814bcce2057.
[INFO]	--> Setting version for github.com/tendermint/go-wire to b6fc872b42d41158a60307db4da051dd6f179415.
[INFO]	--> Setting version for github.com/tendermint/go-crypto to dd20358a264c772b4a83e477b0cfce4c88a7001d.
[INFO]	--> Setting version for github.com/tendermint/tmlibs to 91b4b534ad78e442192c8175db92a06a51064064.
[INFO]	--> Setting version for github.com/tendermint/tendermint to 381fe19335ba8825e04d1d0fefa5cac709bb7178.
[INFO]	--> Setting version for golang.org/x/crypto to 0fcca4842a8d74bfddc2c96a073bd2a4d2a7a2e8.
[INFO]	--> Setting version for github.com/tendermint/iavl to 594cc0c062a7174475f0ab654384038d77067917.
[INFO]	--> Setting version for golang.org/x/net to 42fe2e1c20de1054d3d30f82cc9fb5b41e2e3767.
[INFO]	--> Setting version for github.com/davecgh/go-spew to ecdeabc65495df2dec95d7c4a4c3e021903035e5.
[INFO]	--> Setting version for golang.org/x/text to e19ae1496984b1c655b8044a65c0300a3c878dd3.
[INFO]	--> Setting version for google.golang.org/genproto to a8101f21cf983e773d0c1133ebc5424792003214.
[INFO]	--> Setting version for google.golang.org/grpc to 401e0e00e4bb830a10496d64cd95e068c5bf50de.
[INFO]	--> Setting version for golang.org/x/sys to a3f2cbd54cf5dfe3fbaccf76375fdb12f67654c8.
[INFO]	--> Setting version for github.com/pmezard/go-difflib to 792786c7400a136282c1664665ae0a8db921c6c2.
[INFO]	--> Setting version for gopkg.in/yaml.v2 to 0e4404da71227dcc02fb1deee803d93e86d08f72.
[INFO]	--> Setting version for github.com/stretchr/testify to 87b1dfb5b2fa649f52695dd9eae19abe404a4308.
[INFO]	--> Setting version for gopkg.in/go-playground/validator.v9 to b1f51f36f1c98cc97f777d6fc9d4b05eaa0cabb5.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/btcsuite/btcd
[INFO]	--> Exporting github.com/bgentry/speakeasy
[INFO]	--> Exporting github.com/BurntSushi/toml
[INFO]	--> Exporting github.com/ethanfrey/ledger
[INFO]	--> Exporting github.com/fsnotify/fsnotify
[INFO]	--> Exporting github.com/ethanfrey/hid
[INFO]	--> Exporting github.com/ebuchman/fail-test
[INFO]	--> Exporting github.com/go-kit/kit
[INFO]	--> Exporting github.com/go-playground/universal-translator
[INFO]	--> Exporting github.com/gorilla/websocket
[INFO]	--> Exporting github.com/go-stack/stack
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/golang/snappy
[INFO]	--> Exporting github.com/gorilla/context
[INFO]	--> Exporting github.com/go-logfmt/logfmt
[INFO]	--> Exporting github.com/gorilla/mux
[INFO]	--> Exporting github.com/hashicorp/hcl
[INFO]	--> Exporting github.com/howeyc/crc16
[INFO]	--> Exporting github.com/go-playground/locales
[INFO]	--> Exporting github.com/inconshreveable/mousetrap
[INFO]	--> Exporting github.com/jmhodges/levigo
[INFO]	--> Exporting github.com/kr/logfmt
[INFO]	--> Exporting github.com/mitchellh/mapstructure
[INFO]	--> Exporting github.com/pkg/errors
[INFO]	--> Exporting github.com/pelletier/go-toml
[INFO]	--> Exporting github.com/magiconair/properties
[INFO]	--> Exporting github.com/mattn/go-isatty
[INFO]	--> Exporting github.com/rcrowley/go-metrics
[INFO]	--> Exporting github.com/spf13/afero
[INFO]	--> Exporting github.com/spf13/cast
[INFO]	--> Exporting github.com/spf13/cobra
[INFO]	--> Exporting github.com/spf13/jwalterweatherman
[INFO]	--> Exporting github.com/spf13/pflag
[INFO]	--> Exporting github.com/spf13/viper
[INFO]	--> Exporting github.com/syndtr/goleveldb
[INFO]	--> Exporting github.com/tendermint/abci
[INFO]	--> Exporting github.com/tendermint/ed25519
[INFO]	--> Exporting github.com/tendermint/go-crypto
[INFO]	--> Exporting github.com/tendermint/go-wire
[INFO]	--> Exporting github.com/tendermint/iavl
[INFO]	--> Exporting github.com/tendermint/tmlibs
[INFO]	--> Exporting github.com/tendermint/tendermint
[INFO]	--> Exporting golang.org/x/crypto
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting google.golang.org/genproto
[INFO]	--> Exporting google.golang.org/grpc
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	--> Exporting gopkg.in/go-playground/validator.v9
[INFO]	--> Exporting github.com/pmezard/go-difflib
[INFO]	--> Exporting github.com/stretchr/testify
[INFO]	Replacing existing vendor dependencies
cd ./examples/basecoin && make install
../../../../../golang/src/github.com/tendermint/go-crypto/nano/keys.go:9:2: cannot find package "github.com/ethanfrey/ledger" in any of:
	/usr/local/opt/go/libexec/src/github.com/ethanfrey/ledger (from $GOROOT)
	/Users/johndpope/golang/src/github.com/ethanfrey/ledger (from $GOPATH)
../../../../../golang/src/github.com/cosmos/cosmos-sdk/client/rest/keys.go:6:2: cannot find package "github.com/gorilla/mux" in any of:
	/usr/local/opt/go/libexec/src/github.com/gorilla/mux (from $GOROOT)
	/Users/johndpope/golang/src/github.com/gorilla/mux (from $GOPATH)
make[1]: *** [install] Error 1

**Comment by ethanfrey** [comment]
Sorry for the late reply, but this whole thing is being phased out with all the issues trying to get hid to compile on various platforms (see my hid fork). Newer versions of cosmos-sdk remove this dependency. 

If you can recommend a pure-go HID library, I can try to update this. But it taught me the perils of using cgo with a not-super-actively-maintained library, when you want easy cross-platform support.
